/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LANA Project
-/
module

public import Mathlib.FieldTheory.Galois.Profinite
public import Mathlib.FieldTheory.KrullTopology
public import Mathlib.RingTheory.Valuation.ValuationSubring
public import Mathlib.Topology.Algebra.ClopenNhdofOne
public import Mathlib.Topology.Algebra.Category.ProfiniteGrp.Basic

/-!
# Galois-theoretic fundamental groups: inertia and maximal unramified extensions

Let `Ω / P` be a Galois extension (in practice: `Ω` an algebraic closure of the function field
of a curve, `P` a perfect subfield over which `Ω` is algebraic). For a normal integral curve
`X` with function field `L ⊆ Ω` (finite over `P`), the étale fundamental group of `X` is
`Gal(Ω_X / L)`, where `Ω_X ⊆ Ω` is the maximal extension of `L` unramified at all places of
`L` centered on `X` (SGA 1, Exposé V, Proposition 8.2). By ramification theory `Ω_X` is the
fixed field of the closed normal subgroup of `Gal(Ω / L)` generated by the inertia groups of
the places of `Ω` over the places of `L` centered on `X`, so

  `π₁(X) = Gal(Ω / L) ⧸ ⟨⟨ inertia groups of places centered on X ⟩⟩`.

More generally, for a finite group `Γ` acting on `X` (with `L / F` Galois, `F = L^Γ` the
function field of `X / Γ`), the fundamental group of the quotient stack `[X / Γ]` (the Galois
category of `Γ`-equivariant finite étale covers of `X`) is `Gal(Ω / F) ⧸ N`, with `N` the same
subgroup (the maximal extension of `L` unramified over `X` is Galois over `F`).

This file provides the group-theoretic side of this description, in the ambient profinite
group `Gal(Ω / P)`:

* `GaloisPi1.inertia W`: the inertia group of a valuation subring `W` of `Ω`: the
  automorphisms `σ` with `v_W(σ a − a) < 1` for all `a ∈ W` (acting trivially on the residue
  field of `W`);
* `GaloisPi1.kernel H S`: the closed normal subgroup of `H` generated by `S`;
* `GaloisPi1.pi1 H S`: the profinite group `H ⧸ kernel H S`, for a closed subgroup `H`
  (`QuotientGroup.totallyDisconnectedSpace_of_isClosed`: quotients of profinite groups by closed
  normal subgroups are profinite);
* `GaloisPi1.pi1Map`: the continuous homomorphism induced by `H ≤ H'`, `S ⊆ S'`, and
  `GaloisPi1.pi1Map_isOpenEmbedding`: it is an open embedding when `H` is open, `S = S'` and `S`
  is stable under conjugation by `H'`.
-/

@[expose] public section

universe u v

open scoped Pointwise

section QuotientProfinite

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
  [TotallyDisconnectedSpace G]

/-- The quotient of a profinite group by a closed normal subgroup is totally disconnected. -/
theorem QuotientGroup.totallyDisconnectedSpace_of_isClosed (N : Subgroup G) [N.Normal]
    (hN : IsClosed (N : Set G)) : TotallyDisconnectedSpace (G ⧸ N) := by
  rw [totallyDisconnectedSpace_iff_connectedComponent_one]
  refine Set.eq_singleton_iff_unique_mem.mpr ⟨mem_connectedComponent, ?_⟩
  intro x hx
  obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective x
  by_contra hne
  have hg : g ∉ N := fun h => hne ((QuotientGroup.eq_one_iff g).mpr h)
  have hN' := ProfiniteGrp.closedSubgroup_eq_sInf_open (G := G) ⟨N, hN⟩
  have : g ∉ sInf {U : Subgroup G | IsOpen (U : Set G) ∧ N ≤ U} := by
    rw [← hN']; exact hg
  rw [Subgroup.mem_sInf] at this
  push Not at this
  obtain ⟨U, ⟨hUo, hNU⟩, hgU⟩ := this
  let V : Subgroup (G ⧸ N) := U.map (QuotientGroup.mk' N)
  have hVo : IsOpen (V : Set (G ⧸ N)) := by
    simp only [V, Subgroup.coe_map, QuotientGroup.coe_mk']
    exact QuotientGroup.isOpenMap_coe _ hUo
  have hVc : IsClopen (V : Set (G ⧸ N)) := ⟨Subgroup.isClosed_of_isOpen V hVo, hVo⟩
  have h1 : (1 : G ⧸ N) ∈ (V : Set (G ⧸ N)) := V.one_mem
  have := hVc.connectedComponent_subset h1 hx
  obtain ⟨u, hu, hug⟩ := this
  apply hgU
  have : u⁻¹ * g ∈ N := by
    rw [← QuotientGroup.eq]; exact hug
  have := U.mul_mem hu (hNU this)
  simpa using this

end QuotientProfinite

namespace GaloisPi1

variable {P : Type u} {Ω : Type u} [Field P] [Field Ω] [Algebra P Ω]

/-- **The inertia group** of a valuation subring `W` of `Ω`: the automorphisms `σ` acting
trivially on the residue field of `W`, i.e. with `v_W(σ a − a) < 1` for all `a ∈ W` (such a `σ`
maps `W` into itself, hence lies in the decomposition group of `W`). -/
def inertia (W : ValuationSubring Ω) : Set (Ω ≃ₐ[P] Ω) :=
  {σ | ∀ a ∈ W, W.valuation (σ a - a) < 1}

variable (H : Subgroup (Ω ≃ₐ[P] Ω)) (S : Set (Ω ≃ₐ[P] Ω))

/-- The `H`-conjugates of the elements of `S`. -/
def conjSet : Set (Ω ≃ₐ[P] Ω) := {x | ∃ h ∈ H, ∃ s ∈ S, x = h * s * h⁻¹}

/-- **The closed subgroup generated by the `H`-conjugates of `S`** (for `S ⊆ H` and `H` closed:
the closed normal subgroup of `H` generated by `S`). -/
def ambientKernel : Subgroup (Ω ≃ₐ[P] Ω) :=
  (Subgroup.closure (conjSet H S)).topologicalClosure

lemma conj_mem_ambientKernel {h : Ω ≃ₐ[P] Ω} (hh : h ∈ H) {n : Ω ≃ₐ[P] Ω}
    (hn : n ∈ ambientKernel H S) : h * n * h⁻¹ ∈ ambientKernel H S := by
  let c : (Ω ≃ₐ[P] Ω) →* (Ω ≃ₐ[P] Ω) := MulAut.conj h
  have hc : Continuous c := by
    change Continuous fun x => h * x * h⁻¹
    fun_prop
  have hcl : Subgroup.closure (conjSet H S) ≤ (ambientKernel H S).comap c := by
    rw [Subgroup.closure_le]
    rintro _ ⟨g, hg, t, ht, rfl⟩
    refine Subgroup.le_topologicalClosure _ (Subgroup.subset_closure ?_)
    exact ⟨h * g, H.mul_mem hh hg, t, ht, by simp [c, MulAut.conj_apply, mul_assoc]⟩
  have : ambientKernel H S ≤ (ambientKernel H S).comap c := by
    apply Subgroup.topologicalClosure_minimal _ hcl
    exact (Subgroup.isClosed_topologicalClosure _).preimage hc
  exact this hn

lemma isClosed_ambientKernel : IsClosed (ambientKernel H S : Set (Ω ≃ₐ[P] Ω)) :=
  Subgroup.isClosed_topologicalClosure _

/-- **The closed normal subgroup of `H` generated by `S`** (in practice: by the inertia groups
of the places centered on a curve). -/
def kernel : Subgroup H := (ambientKernel H S).subgroupOf H

instance : (kernel H S).Normal where
  conj_mem n hn g := by
    simp only [kernel, Subgroup.mem_subgroupOf] at hn ⊢
    simpa using conj_mem_ambientKernel H S g.2 hn

lemma isClosed_kernel : IsClosed (kernel H S : Set H) :=
  (isClosed_ambientKernel H S).preimage continuous_subtype_val

variable [IsGalois P Ω]

lemma compactSpace_of_isClosed (hH : IsClosed (H : Set (Ω ≃ₐ[P] Ω))) : CompactSpace H :=
  isCompact_iff_compactSpace.mp hH.isCompact

/-- **The Galois-theoretic fundamental group** `H ⧸ ⟨⟨S⟩⟩` (closed normal subgroup), a
profinite group when `H` is closed. -/
noncomputable def pi1 (hH : IsClosed (H : Set (Ω ≃ₐ[P] Ω))) : ProfiniteGrp.{u} :=
  haveI := compactSpace_of_isClosed H hH
  haveI := QuotientGroup.totallyDisconnectedSpace_of_isClosed (kernel H S) (isClosed_kernel H S)
  ProfiniteGrp.of (H ⧸ kernel H S)

variable {H S}

omit [IsGalois P Ω] in
lemma ambientKernel_mono {H' : Subgroup (Ω ≃ₐ[P] Ω)} {S' : Set (Ω ≃ₐ[P] Ω)} (hH : H ≤ H')
    (hS : S ⊆ S') : ambientKernel H S ≤ ambientKernel H' S' := by
  refine Subgroup.topologicalClosure_mono (Subgroup.closure_mono ?_)
  rintro _ ⟨h, hh, t, ht, rfl⟩
  exact ⟨h, hH hh, t, hS ht, rfl⟩

omit [IsGalois P Ω] in
lemma kernel_le_comap {H' : Subgroup (Ω ≃ₐ[P] Ω)} {S' : Set (Ω ≃ₐ[P] Ω)} (hH : H ≤ H')
    (hS : S ⊆ S') : kernel H S ≤ (kernel H' S').comap (Subgroup.inclusion hH) := by
  intro x hx
  simp only [kernel, Subgroup.mem_comap, Subgroup.mem_subgroupOf] at hx ⊢
  exact ambientKernel_mono hH hS hx

/-- The homomorphism of fundamental groups induced by `H ≤ H'`, `S ⊆ S'`. -/
noncomputable def pi1Map {H' : Subgroup (Ω ≃ₐ[P] Ω)} {S' : Set (Ω ≃ₐ[P] Ω)}
    (hHc : IsClosed (H : Set (Ω ≃ₐ[P] Ω))) (hH'c : IsClosed (H' : Set (Ω ≃ₐ[P] Ω)))
    (hH : H ≤ H') (hS : S ⊆ S') : pi1 H S hHc →* pi1 H' S' hH'c :=
  QuotientGroup.map _ _ (Subgroup.inclusion hH) (kernel_le_comap hH hS)

lemma pi1Map_mk {H' : Subgroup (Ω ≃ₐ[P] Ω)} {S' : Set (Ω ≃ₐ[P] Ω)}
    (hHc : IsClosed (H : Set (Ω ≃ₐ[P] Ω))) (hH'c : IsClosed (H' : Set (Ω ≃ₐ[P] Ω)))
    (hH : H ≤ H') (hS : S ⊆ S') (x : H) :
    pi1Map hHc hH'c hH hS (QuotientGroup.mk x : H ⧸ kernel H S) =
      (QuotientGroup.mk (Subgroup.inclusion hH x) : H' ⧸ kernel H' S') := rfl

lemma continuous_pi1Map {H' : Subgroup (Ω ≃ₐ[P] Ω)} {S' : Set (Ω ≃ₐ[P] Ω)}
    (hHc : IsClosed (H : Set (Ω ≃ₐ[P] Ω))) (hH'c : IsClosed (H' : Set (Ω ≃ₐ[P] Ω)))
    (hH : H ≤ H') (hS : S ⊆ S') : Continuous (pi1Map hHc hH'c hH hS) := by
  change Continuous (QuotientGroup.map (kernel H S) (kernel H' S') (Subgroup.inclusion hH)
    (kernel_le_comap hH hS))
  rw [(QuotientGroup.isQuotientMap_mk (kernel H S)).continuous_iff]
  exact QuotientGroup.continuous_mk.comp (continuous_inclusion hH)

/-- **Open embedding criterion**: if `H` is open, `S ⊆ H`, and `S` is stable under conjugation
by `H'`, the induced map `H ⧸ ⟨⟨S⟩⟩ → H' ⧸ ⟨⟨S⟩⟩` is an open embedding. -/
theorem isOpenEmbedding_pi1Map {H' : Subgroup (Ω ≃ₐ[P] Ω)}
    (hHc : IsClosed (H : Set (Ω ≃ₐ[P] Ω))) (hH'c : IsClosed (H' : Set (Ω ≃ₐ[P] Ω)))
    (hH : H ≤ H') (hHo : IsOpen (H : Set (Ω ≃ₐ[P] Ω)))
    (hconj : ∀ h ∈ H', ∀ s ∈ S, h * s * h⁻¹ ∈ S) :
    Topology.IsOpenEmbedding (pi1Map hHc hH'c hH (subset_refl S)) := by
  have hSS : ∀ K : Subgroup (Ω ≃ₐ[P] Ω), K ≤ H' → 1 ∈ K →
      conjSet K S = S := by
    intro K hK h1
    ext x
    constructor
    · rintro ⟨h, hh, t, ht, rfl⟩; exact hconj h (hK hh) t ht
    · intro hx; exact ⟨1, h1, x, hx, by simp⟩
  have hker : ambientKernel H S = ambientKernel H' S := by
    simp only [ambientKernel, hSS H hH H.one_mem, hSS H' le_rfl H'.one_mem]
  refine Topology.IsOpenEmbedding.of_continuous_injective_isOpenMap
    (continuous_pi1Map hHc hH'c hH _) ?_ ?_
  · rw [injective_iff_map_eq_one]
    intro a ha
    obtain ⟨x, rfl⟩ := QuotientGroup.mk_surjective a
    change (QuotientGroup.mk (Subgroup.inclusion hH x) : H' ⧸ kernel H' S) = 1 at ha
    change (QuotientGroup.mk x : H ⧸ kernel H S) = 1
    rw [QuotientGroup.eq_one_iff] at ha
    rw [QuotientGroup.eq_one_iff]
    simp only [kernel, Subgroup.mem_subgroupOf] at ha ⊢
    rw [hker]
    exact ha
  · intro U hU
    have hU' : IsOpen (QuotientGroup.mk ⁻¹' U : Set H) :=
      QuotientGroup.continuous_mk.isOpen_preimage _ hU
    have himg : pi1Map hHc hH'c hH (subset_refl S) '' U =
        QuotientGroup.mk '' (Subgroup.inclusion hH '' (QuotientGroup.mk ⁻¹' U)) := by
      ext y
      constructor
      · rintro ⟨a, ha, rfl⟩
        obtain ⟨x, rfl⟩ := QuotientGroup.mk_surjective a
        exact ⟨Subgroup.inclusion hH x, ⟨x, ha, rfl⟩, rfl⟩
      · rintro ⟨_, ⟨x, hx, rfl⟩, rfl⟩
        exact ⟨QuotientGroup.mk x, hx, rfl⟩
    rw [himg]
    refine QuotientGroup.isOpenMap_coe _ ?_
    -- the inclusion of the open subgroup `H` into `H'` is an open map
    obtain ⟨V, hV, hVU⟩ := isOpen_induced_iff.mp hU'
    have : Subgroup.inclusion hH '' (QuotientGroup.mk ⁻¹' U) =
        ((↑) : H' → Ω ≃ₐ[P] Ω) ⁻¹' (V ∩ H) := by
      ext y
      constructor
      · rintro ⟨x, hx, rfl⟩
        refine ⟨?_, x.2⟩
        rw [← hVU] at hx
        exact hx
      · rintro ⟨hyV, hyH⟩
        refine ⟨⟨y, hyH⟩, ?_, rfl⟩
        rw [← hVU]
        exact hyV
    rw [this]
    exact (hV.inter hHo).preimage continuous_subtype_val

/-- **Open embedding criterion** (variant): if `H` is open, `S = S' ⊆ H`, and `S` is stable under
conjugation by `H'`, the induced map `H ⧸ ⟨⟨S⟩⟩ → H' ⧸ ⟨⟨S'⟩⟩` is an open embedding. -/
theorem isOpenEmbedding_pi1Map' {H' : Subgroup (Ω ≃ₐ[P] Ω)} {S' : Set (Ω ≃ₐ[P] Ω)}
    (hHc : IsClosed (H : Set (Ω ≃ₐ[P] Ω))) (hH'c : IsClosed (H' : Set (Ω ≃ₐ[P] Ω)))
    (hH : H ≤ H') (hS : S ⊆ S') (hS' : S' ⊆ S) (hHo : IsOpen (H : Set (Ω ≃ₐ[P] Ω)))
    (hconj : ∀ h ∈ H', ∀ s ∈ S, h * s * h⁻¹ ∈ S) :
    Topology.IsOpenEmbedding (pi1Map hHc hH'c hH hS) := by
  obtain rfl : S = S' := subset_antisymm hS hS'
  exact isOpenEmbedding_pi1Map hHc hH'c hH hHo hconj

end GaloisPi1
