name = "pi1"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Pi1"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
linter.style.longLine = true
backward.isDefEq.respectTransparency = false
maxSynthPendingDepth = 3
backward.defeqAttrib.useBackward = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "Pi1"
