module  -- shake: keep-all --deprecated_module: ignore

public import Pi1.FundamentalGroup.AffineAnd
public import Pi1.FundamentalGroup.AffineColimits
public import Pi1.FundamentalGroup.FiniteEtale
public import Pi1.FundamentalGroup.Galois
public import Pi1.FundamentalGroup.Point
public import Pi1.FundamentalGroup.Rank
public import Pi1.Mathlib.AlgebraicGeometry.Limits
public import Pi1.Mathlib.AlgebraicGeometry.Morphisms.Finite
public import Pi1.Mathlib.AlgebraicGeometry.Morphisms.Flat
public import Pi1.Mathlib.CategoryTheory.Galois.IsFundamentalGroup
public import Pi1.Mathlib.CategoryTheory.Limits.MorphismProperty
public import Pi1.Mathlib.RingTheory.Flat.Equalizer
public import Pi1.Mathlib.RingTheory.Geometric
public import Pi1.Mathlib.RingTheory.Ideal.Quotient.Operations
public import Pi1.Mathlib.RingTheory.RingHom.Etale
public import Pi1.Mathlib.RingTheory.RingHom.Finite
public import Pi1.Mathlib.RingTheory.RingHom.Smooth
public import Pi1.Mathlib.RingTheory.TensorProduct.Basic
public import Pi1.Orbicurve.Core
public import Pi1.Orbicurve.Elliptic
public import Pi1.Orbicurve.EtaleInertia
public import Pi1.Orbicurve.GaloisPi1
public import Pi1.Orbicurve.IntegralClosure
public import Pi1.Orbicurve.Morphisms
public import Pi1.Orbicurve.Subfield
public import Pi1.Orbicurve.SubfieldGalois
public import Pi1.Orbicurve.ValuationInertia
public import Pi1.Orbifold.Etale
public import Pi1.Orbifold.EtaleMathlib
public import Pi1.Orbifold.EtaleProfinite
public import Pi1.Orbifold.FibreAut
public import Pi1.Orbifold.GaloisAction
public import Pi1.Orbifold.GaloisData
public import Pi1.Orbifold.Level
public import Pi1.RingTheory.FiniteEtale.Basic
public import Pi1.RingTheory.FiniteEtale.Descent
public import Pi1.RingTheory.FiniteEtale.Equalizer
public import Pi1.RingTheory.KerTensor
public import Pi1.RingTheory.Smooth.StandardSmoothSmooth
public import Pi1.RingTheory.Transcendence
public import Pi1.RingTheory.UnramifiedValuation
