name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1

      #- name: Cache documentation
      #  uses: actions/cache@v4
      #  with:
      #    path: docs/build
      #    key: MathlibDoc-${{ hashFiles('lake-manifest.json') }}
      #    restore-keys: MathlibDoc-

      #- name: Build documentation
      #  run: scripts/build_docs.sh

      #- name: Upload docs
      #  uses: actions/upload-pages-artifact@v3
      #  with:
      #    path: docs/build

      #- name: Deploy to GitHub Pages
      #  id: deployment
      #  uses: actions/deploy-pages@v4
